# ISA Configurations
isa_params:  
  xlen : 32

# Microarchitectural Configurations
microarch_params:
  # Multicore configurations
  num_harts : 1

  # Branch/Jump Configurations
  br_predictor_type : "not_taken"
  btb_size : 128 
  btb_assoc : 1
  use_ras : "false"
  
  # Cache configurations
  cache_config  : "separate"
  dcache_type   : "pass_through"
  icache_type   : "pass_through"
  
  # Bus configurations
  bus_endianness      : "big"
  bus_interface_type  : "generic_bus_if"

  # Sparisty Optimizations
  sparce_enabled : "disabled"

  # RV32C
  rv32c_enabled : "disabled"
  
  # Halt
  infinite_loop_halts : "true"

  # base ISA 
  base_isa: "RV32I"

# RISC-MGMT Extension Configuration
risc_mgmt_params:
  standard_extensions:
  nonstandard_extensions:

