# ISA Configurations
isa_params:  
  xlen : 32
  pmp_minimum_granularity : "64K"
  supervisor_enabled : "disabled"
  address_translation_enabled : "disabled"
  isa: "rv32izifencei_zicsr"

# Microarchitectural Configurations
microarch_params:
  # Multicore configurations
  num_harts : 1

  # Branch/Jump Configurations
  br_predictor_type : "not_taken"
  btb_size : 128 
  use_ras : "false"
  
  # Cache configurations
  cache_config  : "separate"
  dcache_type   : "pass_through"
  icache_type   : "pass_through"
  
  # Bus configurations
  bus_endianness      : "big"
  bus_interface_type  : "generic_bus_if"

  # Sparisty Optimizations
  sparce_enabled : "disabled"

  # Halt
  infinite_loop_halts : "true"
