#Auto generated by Edalize

TOP_MODULE        := top_core
VC_FILE           := socet_riscv_RISCVBusiness_0.1.0.vc
VERILATOR_OPTIONS := -Wno-SYMRSVDWORD -Wno-lint --trace --trace-fst --trace-structs
MAKE_OPTIONS      := -j
