// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop_core.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vtop_core_top_core.h"

VL_ATTR_COLD void Vtop_core_top_core___eval_initial__TOP__top_core(Vtop_core_top_core* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vtop_core_top_core___eval_initial__TOP__top_core\n"); );
    // Init
    VlWide<3>/*95:0*/ __Vtemp_h8015d4ed__0;
    // Body
    __Vtemp_h8015d4ed__0[0U] = 0x2e6c6f67U;
    __Vtemp_h8015d4ed__0[1U] = 0x72616365U;
    __Vtemp_h8015d4ed__0[2U] = 0x74U;
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__fptr = VL_FOPEN_NN(
                                                                                VL_CVT_PACK_STR_NW(3, __Vtemp_h8015d4ed__0)
                                                                                , 
                                                                                std::string{"w"});
}

VL_ATTR_COLD void Vtop_core_top_core___eval_final__TOP__top_core(Vtop_core_top_core* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vtop_core_top_core___eval_final__TOP__top_core\n"); );
    // Body
    VL_FCLOSE_I(vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__fptr); vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__fptr = 0;
}

VL_ATTR_COLD void Vtop_core_top_core___ctor_var_reset(Vtop_core_top_core* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+      Vtop_core_top_core___ctor_var_reset\n"); );
    // Body
    vlSelf->CLK = VL_RAND_RESET_I(1);
    vlSelf->nRST = VL_RAND_RESET_I(1);
    vlSelf->mtime = VL_RAND_RESET_Q(64);
    vlSelf->wfi = VL_RAND_RESET_I(1);
    vlSelf->halt = VL_RAND_RESET_I(1);
    vlSelf->busy = VL_RAND_RESET_I(1);
    vlSelf->rdata = VL_RAND_RESET_I(32);
    vlSelf->ren = VL_RAND_RESET_I(1);
    vlSelf->wen = VL_RAND_RESET_I(1);
    vlSelf->byte_en = VL_RAND_RESET_I(4);
    vlSelf->addr = VL_RAND_RESET_I(32);
    vlSelf->wdata = VL_RAND_RESET_I(32);
    vlSelf->ext_int = VL_RAND_RESET_I(1);
    vlSelf->ext_int_clear = VL_RAND_RESET_I(1);
    vlSelf->soft_int = VL_RAND_RESET_I(1);
    vlSelf->soft_int_clear = VL_RAND_RESET_I(1);
    vlSelf->timer_int = VL_RAND_RESET_I(1);
    vlSelf->timer_int_clear = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__fetch_stage_i__DOT__pc = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__fetch_stage_i__DOT__npc = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__rs1_post_fwd = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__rs2_post_fwd = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__imm_I_ext = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__mal_addr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT__maybe_illegal = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT__sr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT__add_sub = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT___VdfgExtracted___h7d703271__0 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__op_b = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__adder_out = VL_RAND_RESET_Q(33);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__op_a_ext = VL_RAND_RESET_Q(33);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__op_b_ext = VL_RAND_RESET_Q(33);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__jump_calc__DOT__jump_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__lt = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__eq = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__ltu = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__adder_out = VL_RAND_RESET_Q(33);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__op_2_ext = VL_RAND_RESET_Q(33);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__g_rfile_select__DOT__rf__DOT__registers);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__dload_ext = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__mal_addr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__byte_en_standard = VL_RAND_RESET_I(4);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__ifence_reg = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__ifence_pulse = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__iflushed = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__dflushed = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__iflush_done_reg = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__dflush_done_reg = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__fptr = 0;
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__branch_jump = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__wait_for_imem = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__wait_for_dmem = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__fetch_busy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__execute_busy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__mem_busy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__ex_flush_hazard = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__exception = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__intr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mstatus = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mstatus_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mie = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mie_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtvec = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtvec_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mscratch = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mscratch_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mepc = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mepc_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcause = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcause_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtval = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtval_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mip = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mip_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounteren = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounteren_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounterinhibit = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounterinhibit_next = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__cycles_full = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__cf_next = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__instret_full = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__if_next = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__nxt_csr_val = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__invalid_csr_priv = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__invalid_csr_addr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__csr_operation = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_mcycle = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_minstret = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_mcycleh = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_minstreth = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__ex_src = VL_RAND_RESET_I(31);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__exception = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__int_src = VL_RAND_RESET_I(31);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__interrupt = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__interrupt_fired = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(512, vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__pma_regs);
    VL_RAND_RESET_W(512, vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__nxt_pma_regs);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__active_reg_d = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__active_reg_i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__pma_cfg_d = VL_RAND_RESET_I(16);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__pma_cfg_i = VL_RAND_RESET_I(16);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__new_val = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(128, vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__pmp_cfg_regs);
    VL_RAND_RESET_W(128, vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__nxt_pmp_cfg);
    VL_RAND_RESET_W(512, vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__pmp_addr_regs);
    VL_RAND_RESET_W(512, vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__nxt_pmp_addr);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__new_cfg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_cfg_match = VL_RAND_RESET_I(16);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_match = VL_RAND_RESET_I(8);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_match_found = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_prot_fault = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_cfg_match = VL_RAND_RESET_I(16);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_match = VL_RAND_RESET_I(8);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_match_found = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_prot_fault = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__0__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__1__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__2__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__3__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__4__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__5__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__6__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__7__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__8__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__9__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__10__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__11__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__12__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__13__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__14__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__15__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__0__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__1__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__2__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__3__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__4__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__5__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__6__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__7__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__8__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__9__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__10__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__11__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__12__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__13__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__14__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__15__KET____DOT__matcher____pinNumber5 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__mode__DOT__curr_priv_level = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__mode__DOT__next_priv_level = VL_RAND_RESET_I(2);
    vlSelf->CORE__DOT__sep_caches__DOT____Vcellout__genblk1__DOT__dcache__flush_done = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT____Vcellout__genblk2__DOT__icache__flush_done = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__flush_idx = VL_RAND_RESET_I(6);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_flush_idx = VL_RAND_RESET_I(6);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__word_num = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_word_num = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__enable_word_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__clear_word_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__clear_flush_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__enable_flush_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__enable_flush_count_nowb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__state = 0;
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_state = 0;
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__ridx = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__last_used = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_last_used = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__read_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_read_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__decoded_req_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_decoded_req_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__hit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__pass_through = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__hit_data = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__hit_idx = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(372, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramWrite);
    VL_RAND_RESET_W(372, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramMask);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramWEN = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramSEL = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(372, vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vcellout__SRAM____pinNumber4);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__unnamedblk1__DOT__i = 0;
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__0 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__1 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__2 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__3 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__4 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__5 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__6 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h75d3f992__0 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hc69e7196__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h033cbfa6__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h325132d4__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hbf233a89__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hbf233a89__1 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h003574db__0 = VL_RAND_RESET_I(27);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h325132d4__1 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h7d1a0219__0 = VL_RAND_RESET_I(27);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hb7f2d31d__0 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_he3f90764__0 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hbe55c246__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h325527b6__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h0f1df81b__0);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h1ee545ae__0);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h0f1df81b__1);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h1ee545ae__1);
    VL_RAND_RESET_W(1488, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__SRAM__DOT__sramMemory);
    VL_RAND_RESET_W(1488, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__SRAM__DOT__n_sramMemory);
    VL_RAND_RESET_W(372, vlSelf->CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__SRAM__DOT____Vlvbound_h9e60dea4__0);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__flush_idx = VL_RAND_RESET_I(6);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_flush_idx = VL_RAND_RESET_I(6);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__word_num = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_word_num = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__enable_word_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__clear_word_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__clear_flush_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__enable_flush_count = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__enable_flush_count_nowb = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__state = 0;
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_state = 0;
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__ridx = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__last_used = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_last_used = VL_RAND_RESET_I(2);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__read_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_read_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__decoded_req_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_decoded_req_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__hit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__pass_through = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__hit_data = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__hit_idx = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(372, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramWrite);
    VL_RAND_RESET_W(372, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramMask);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramWEN = VL_RAND_RESET_I(1);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramSEL = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(372, vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vcellout__SRAM____pinNumber4);
    vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__unnamedblk1__DOT__i = 0;
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h325132d4__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hbf233a89__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hbf233a89__1 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h003574db__0 = VL_RAND_RESET_I(27);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h325132d4__1 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h7d1a0219__0 = VL_RAND_RESET_I(27);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hb7f2d31d__0 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_he3f90764__0 = VL_RAND_RESET_I(32);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hbe55c246__0 = VL_RAND_RESET_I(1);
    vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h325527b6__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h0f1df81b__0);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h1ee545ae__0);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h0f1df81b__1);
    VL_RAND_RESET_W(93, vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h1ee545ae__1);
    VL_RAND_RESET_W(1488, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__SRAM__DOT__sramMemory);
    VL_RAND_RESET_W(1488, vlSelf->__PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__SRAM__DOT__n_sramMemory);
    VL_RAND_RESET_W(372, vlSelf->CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__SRAM__DOT____Vlvbound_h9e60dea4__0);
    vlSelf->__PVT__CORE__DOT__mc__DOT__current_state = 0;
    vlSelf->__PVT__CORE__DOT__mc__DOT__next_state = 0;
    vlSelf->__PVT__CORE__DOT__g_generic_bus_if__DOT__bt__DOT__next_busy = VL_RAND_RESET_I(1);
    vlSelf->__Vdly__CORE__DOT__pipeline__DOT__fetch_stage_i__DOT__pc = VL_RAND_RESET_I(32);
}
