// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop_core.h for the primary calling header

#ifndef VERILATED_VTOP_CORE_TOP_CORE_H_
#define VERILATED_VTOP_CORE_TOP_CORE_H_  // guard

#include "verilated.h"

class Vtop_core__Syms;
class Vtop_core_generic_bus_if;
class Vtop_core_risc_mgmt_if;
class Vtop_core_prv_pipeline_if;
class Vtop_core_cache_control_if;
class Vtop_core_sparce_pipeline_if;
class Vtop_core_rv32c_if;
class Vtop_core_tspp_fetch_execute_if;
class Vtop_core_tspp_hazard_unit_if;
class Vtop_core_stage3_fetch_execute_if;
class Vtop_core_stage3_mem_pipe_if;
class Vtop_core_stage3_hazard_unit_if;
class Vtop_core_stage3_forwarding_unit_if;
class Vtop_core_control_unit_if;
class Vtop_core_alu_if;
class Vtop_core_branch_res_if;
class Vtop_core_priv_1_12_internal_if;
class Vtop_core_priv_ext_if;


class Vtop_core_top_core final : public VerilatedModule {
  public:
    // CELLS
    Vtop_core_generic_bus_if* __PVT__gen_bus_if;
    Vtop_core_generic_bus_if* __PVT__CORE__DOT__tspp_icache_gen_bus_if;
    Vtop_core_generic_bus_if* __PVT__CORE__DOT__tspp_dcache_gen_bus_if;
    Vtop_core_generic_bus_if* __PVT__CORE__DOT__icache_mc_if;
    Vtop_core_generic_bus_if* __PVT__CORE__DOT__dcache_mc_if;
    Vtop_core_generic_bus_if* __PVT__CORE__DOT__pipeline_trans_if;
    Vtop_core_risc_mgmt_if* __PVT__CORE__DOT__rm_if;
    Vtop_core_prv_pipeline_if* __PVT__CORE__DOT__prv_pipe_if;
    Vtop_core_cache_control_if* __PVT__CORE__DOT__cc_if;
    Vtop_core_sparce_pipeline_if* __PVT__CORE__DOT__sparce_if;
    Vtop_core_rv32c_if* __PVT__CORE__DOT__rv32cif;
    Vtop_core_tspp_fetch_execute_if* __PVT__CORE__DOT__fetch_ex_if;
    Vtop_core_tspp_hazard_unit_if* __PVT__CORE__DOT__hazard_if;
    Vtop_core_stage3_fetch_execute_if* __PVT__CORE__DOT__pipeline__DOT__fetch_ex_if;
    Vtop_core_stage3_mem_pipe_if* __PVT__CORE__DOT__pipeline__DOT__mem_pipe_if;
    Vtop_core_stage3_hazard_unit_if* __PVT__CORE__DOT__pipeline__DOT__hazard_if;
    Vtop_core_stage3_forwarding_unit_if* __PVT__CORE__DOT__pipeline__DOT__fw_if;
    Vtop_core_control_unit_if* __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu_if;
    Vtop_core_alu_if* __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu_if;
    Vtop_core_branch_res_if* __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_if;
    Vtop_core_priv_1_12_internal_if* __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__prv_intern_if;
    Vtop_core_priv_ext_if* __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__priv_ext_pma_if;
    Vtop_core_priv_ext_if* __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__priv_ext_pmp_if;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(CLK,0,0);
        VL_IN8(nRST,0,0);
        VL_OUT8(wfi,0,0);
        VL_OUT8(halt,0,0);
        VL_IN8(busy,0,0);
        VL_OUT8(ren,0,0);
        VL_OUT8(wen,0,0);
        VL_OUT8(byte_en,3,0);
        VL_IN8(ext_int,0,0);
        VL_IN8(ext_int_clear,0,0);
        VL_IN8(soft_int,0,0);
        VL_IN8(soft_int_clear,0,0);
        VL_IN8(timer_int,0,0);
        VL_IN8(timer_int_clear,0,0);
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__mal_addr;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT__maybe_illegal;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT__sr;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT__add_sub;
        CData/*3:0*/ CORE__DOT__pipeline__DOT__execute_stage_i__DOT__cu__DOT___VdfgExtracted___h7d703271__0;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__lt;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__eq;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__ltu;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__mal_addr;
        CData/*3:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__byte_en_standard;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__ifence_reg;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__ifence_pulse;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__iflushed;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__dflushed;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__iflush_done_reg;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__dflush_done_reg;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__branch_jump;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__wait_for_imem;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__wait_for_dmem;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__fetch_busy;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__execute_busy;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__mem_busy;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__ex_flush_hazard;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__exception;
        CData/*0:0*/ __PVT__CORE__DOT__pipeline__DOT__hazard_unit_i__DOT__intr;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__invalid_csr_priv;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__invalid_csr_addr;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__csr_operation;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_mcycle;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_minstret;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_mcycleh;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__inject_minstreth;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__exception;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__interrupt;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__interrupt_fired;
        VlWide<4>/*127:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__pmp_cfg_regs;
        VlWide<4>/*127:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__nxt_pmp_cfg;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__new_cfg;
        CData/*7:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_match;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_match_found;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_prot_fault;
        CData/*7:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_match;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_match_found;
        CData/*0:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_prot_fault;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__0__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__1__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__2__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__3__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__4__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__5__KET____DOT__matcher____pinNumber5;
    };
    struct {
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__6__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__7__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__8__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__9__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__10__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__11__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__12__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__13__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__14__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk1__BRA__15__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__0__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__1__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__2__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__3__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__4__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__5__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__6__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__7__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__8__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__9__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__10__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__11__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__12__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__13__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__14__KET____DOT__matcher____pinNumber5;
        CData/*0:0*/ CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT____Vcellout__genblk2__BRA__15__KET____DOT__matcher____pinNumber5;
        CData/*1:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__mode__DOT__curr_priv_level;
        CData/*1:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__mode__DOT__next_priv_level;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT____Vcellout__genblk1__DOT__dcache__flush_done;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT____Vcellout__genblk2__DOT__icache__flush_done;
        CData/*5:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__flush_idx;
        CData/*5:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_flush_idx;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__word_num;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_word_num;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__enable_word_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__clear_word_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__clear_flush_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__enable_flush_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__enable_flush_count_nowb;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__ridx;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__last_used;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_last_used;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__hit;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__pass_through;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__hit_idx;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramWEN;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramSEL;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hc69e7196__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h033cbfa6__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h325132d4__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hbf233a89__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hbf233a89__1;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h325132d4__1;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hbe55c246__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h325527b6__0;
        CData/*5:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__flush_idx;
        CData/*5:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_flush_idx;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__word_num;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_word_num;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__enable_word_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__clear_word_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__clear_flush_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__enable_flush_count;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__enable_flush_count_nowb;
    };
    struct {
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__ridx;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__last_used;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_last_used;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__hit;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__pass_through;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__hit_idx;
        CData/*0:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramWEN;
        CData/*1:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramSEL;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h325132d4__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hbf233a89__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hbf233a89__1;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h325132d4__1;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hbe55c246__0;
        CData/*0:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h325527b6__0;
        CData/*0:0*/ __PVT__CORE__DOT__g_generic_bus_if__DOT__bt__DOT__next_busy;
        SData/*15:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__pma_cfg_d;
        SData/*15:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__pma_cfg_i;
        SData/*15:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__d_cfg_match;
        SData/*15:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__i_cfg_match;
        VL_IN(rdata,31,0);
        VL_OUT(addr,31,0);
        VL_OUT(wdata,31,0);
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__fetch_stage_i__DOT__pc;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__fetch_stage_i__DOT__npc;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__rs1_post_fwd;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__rs2_post_fwd;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__imm_I_ext;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__op_b;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__jump_calc__DOT__jump_addr;
        VlWide<32>/*1023:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__g_rfile_select__DOT__rf__DOT__registers;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__dload_ext;
        IData/*31:0*/ __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__fptr;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mstatus;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mstatus_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mie;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mie_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtvec;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtvec_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mscratch;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mscratch_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mepc;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mepc_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcause;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcause_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtval;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mtval_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mip;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mip_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounteren;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounteren_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounterinhibit;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__mcounterinhibit_next;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__nxt_csr_val;
        IData/*30:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__ex_src;
        IData/*30:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__int_ex_handler__DOT__int_src;
        VlWide<16>/*511:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__pma_regs;
        VlWide<16>/*511:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__nxt_pma_regs;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__active_reg_d;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__active_reg_i;
        IData/*31:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pma__DOT__new_val;
        VlWide<16>/*511:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__pmp_addr_regs;
        VlWide<16>/*511:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__pmp__DOT__nxt_pmp_addr;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__state;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_state;
    };
    struct {
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__read_addr;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_read_addr;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__decoded_req_addr;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__next_decoded_req_addr;
        QData/*63:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__hit_data;
        VlWide<12>/*371:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vcellout__SRAM____pinNumber4;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__0;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__1;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__2;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__3;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__4;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__5;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h214df0a5__6;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h75d3f992__0;
        IData/*26:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h003574db__0;
        IData/*26:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h7d1a0219__0;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_hb7f2d31d__0;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_he3f90764__0;
        VlWide<47>/*1487:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__SRAM__DOT__sramMemory;
        VlWide<47>/*1487:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__SRAM__DOT__n_sramMemory;
        VlWide<12>/*371:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__SRAM__DOT____Vlvbound_h9e60dea4__0;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__state;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_state;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__read_addr;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_read_addr;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__decoded_req_addr;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__next_decoded_req_addr;
        QData/*63:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__hit_data;
        VlWide<12>/*371:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vcellout__SRAM____pinNumber4;
        IData/*31:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__unnamedblk1__DOT__i;
        IData/*26:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h003574db__0;
        IData/*26:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h7d1a0219__0;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_hb7f2d31d__0;
        IData/*31:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_he3f90764__0;
        VlWide<47>/*1487:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__SRAM__DOT__sramMemory;
        VlWide<47>/*1487:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__SRAM__DOT__n_sramMemory;
        VlWide<12>/*371:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__SRAM__DOT____Vlvbound_h9e60dea4__0;
        IData/*31:0*/ __PVT__CORE__DOT__mc__DOT__current_state;
        IData/*31:0*/ __PVT__CORE__DOT__mc__DOT__next_state;
        IData/*31:0*/ __Vdly__CORE__DOT__pipeline__DOT__fetch_stage_i__DOT__pc;
        VL_IN64(mtime,63,0);
        QData/*32:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__adder_out;
        QData/*32:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__op_a_ext;
        QData/*32:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__alu__DOT__op_b_ext;
        QData/*32:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__adder_out;
        QData/*32:0*/ __PVT__CORE__DOT__pipeline__DOT__execute_stage_i__DOT__branch_res__DOT__op_2_ext;
        QData/*63:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__cycles_full;
        QData/*63:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__cf_next;
        QData/*63:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__instret_full;
        QData/*63:0*/ __PVT__CORE__DOT__priv_wrapper_i__DOT__priv_block_i__DOT__csr__DOT__if_next;
        VlWide<12>/*371:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramWrite;
        VlWide<12>/*371:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT__sramMask;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h0f1df81b__0;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h1ee545ae__0;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h0f1df81b__1;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk1__DOT__dcache__DOT____Vlvbound_h1ee545ae__1;
        VlWide<12>/*371:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramWrite;
        VlWide<12>/*371:0*/ __PVT__CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT__sramMask;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h0f1df81b__0;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h1ee545ae__0;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h0f1df81b__1;
        VlWide<3>/*92:0*/ CORE__DOT__sep_caches__DOT__genblk2__DOT__icache__DOT____Vlvbound_h1ee545ae__1;
    };
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__instr_mnemonic;
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__output_str;
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__src1;
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__src2;
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__dest;
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__operands;
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__csr;
    std::string __PVT__CORE__DOT__pipeline__DOT__mem_stage_i__DOT__cpu_track1__DOT__temp_str;

    // INTERNAL VARIABLES
    Vtop_core__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop_core_top_core(Vtop_core__Syms* symsp, const char* name);
    ~Vtop_core_top_core();
    VL_UNCOPYABLE(Vtop_core_top_core);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    uint32_t get_x28();
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
