
# NC-Sim Command File
# TOOL:	ncsim(64)	15.20-s030
#
#
# You can restore this configuration with:
#
#      ncsim tb_RISCVBusiness_self_test -input /home/asicfab/a/socet14/RISCVBusiness/waveform_scripts/priv.tcl
#

set tcl_prompt1 {puts -nonewline "ncsim> "}
set tcl_prompt2 {puts -nonewline "> "}
set vlog_format %h
set vhdl_format %v
set real_precision 6
set display_unit auto
set time_unit module
set heap_garbage_size -200
set heap_garbage_time 0
set assert_report_level note
set assert_stop_level error
set autoscope yes
set assert_1164_warnings yes
set pack_assert_off {}
set severity_pack_assert_off {note warning}
set assert_output_stop_level failed
set tcl_debug_level 0
set relax_path_name 1
set vhdl_vcdmap XX01ZX01X
set intovf_severity_level ERROR
set probe_screen_format 0
set rangecnst_severity_level ERROR
set textio_severity_level ERROR
set vital_timing_checks_on 1
set vlog_code_show_force 0
set assert_count_attempts 1
set tcl_all64 false
set tcl_runerror_exit false
set assert_report_incompletes 0
set show_force 1
set force_reset_by_reinvoke 0
set tcl_relaxed_literal 0
set probe_exclude_patterns {}
set probe_packed_limit 4k
set probe_unpacked_limit 16k
set assert_internal_msg no
set svseed 1
set assert_reporting_mode 0
alias iprof profile
database -open -shm -into waves.shm waves -default
probe -create -database waves tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.CLK tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.nRST tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mret tb_RISCVBusiness_self_test.prv_intern_if.prv_control.intr tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mie tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mip tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mip_next tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mip_rup tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.csr_rfile_i.mtime tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.csr_rfile_i.mtime_next tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.csr_rfile_i.mtimecmp tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.csr_rfile_i.mtimecmp_next tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mtval tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mtval_next tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mtval_rup tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mstatus tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mstatus_next tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mstatus_rup tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mcause tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mcause_next tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mcause_rup tb_RISCVBusiness_self_test.prv_intern_if.prv_control.soft_int_m tb_RISCVBusiness_self_test.prv_intern_if.prv_control.soft_int_s tb_RISCVBusiness_self_test.prv_intern_if.prv_control.soft_int_u tb_RISCVBusiness_self_test.prv_intern_if.prv_control.timer_int_m tb_RISCVBusiness_self_test.prv_intern_if.prv_control.timer_int_s tb_RISCVBusiness_self_test.prv_intern_if.prv_control.timer_int_u tb_RISCVBusiness_self_test.prv_intern_if.prv_control.clear_timer_int tb_RISCVBusiness_self_test.prv_intern_if.prv_control.ext_int_m tb_RISCVBusiness_self_test.prv_intern_if.prv_control.ext_int_s tb_RISCVBusiness_self_test.prv_intern_if.prv_control.ext_int_u tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.interrupt tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.interrupt_fired tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.interrupt_reg tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.intr_src tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.exception tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.prv_control_i.ex_src tb_RISCVBusiness_self_test.prv_intern_if.prv_control.pipe_clear tb_RISCVBusiness_self_test.prv_intern_if.prv_control.fault_insn_access tb_RISCVBusiness_self_test.prv_intern_if.prv_control.fault_insn_page tb_RISCVBusiness_self_test.prv_intern_if.prv_control.fault_l tb_RISCVBusiness_self_test.prv_intern_if.prv_control.fault_load_page tb_RISCVBusiness_self_test.prv_intern_if.prv_control.fault_s tb_RISCVBusiness_self_test.prv_intern_if.prv_control.fault_store_page tb_RISCVBusiness_self_test.prv_intern_if.prv_control.illegal_insn tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mal_insn tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mal_l tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mal_s tb_RISCVBusiness_self_test.prv_intern_if.prv_control.breakpoint tb_RISCVBusiness_self_test.prv_intern_if.prv_control.env_m tb_RISCVBusiness_self_test.prv_intern_if.prv_control.env_s tb_RISCVBusiness_self_test.prv_intern_if.prv_control.env_u tb_RISCVBusiness_self_test.prv_intern_if.prv_control.ex_rmgmt tb_RISCVBusiness_self_test.prv_intern_if.prv_control.ex_rmgmt_cause tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mepc tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mepc_next tb_RISCVBusiness_self_test.prv_intern_if.prv_control.mepc_rup tb_RISCVBusiness_self_test.prv_intern_if.prv_control.epc tb_RISCVBusiness_self_test.prv_intern_if.swap tb_RISCVBusiness_self_test.prv_intern_if.set tb_RISCVBusiness_self_test.prv_intern_if.clr tb_RISCVBusiness_self_test.prv_intern_if.wdata tb_RISCVBusiness_self_test.prv_intern_if.rdata tb_RISCVBusiness_self_test.DUT.priv_wrapper_i.priv_block_i.csr_rfile_i.rup_data tb_RISCVBusiness_self_test.prv_intern_if.pipe_ctrl.mtvec tb_RISCVBusiness_self_test.prv_intern_if.pipe_ctrl.insert_pc tb_RISCVBusiness_self_test.prv_intern_if.pipe_ctrl.intr tb_RISCVBusiness_self_test.prv_intern_if.pipe_ctrl.mepc tb_RISCVBusiness_self_test.prv_intern_if.mepc_next tb_RISCVBusiness_self_test.prv_intern_if.mepc_rup tb_RISCVBusiness_self_test.prv_intern_if.pipe_ctrl.priv_pc tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.control_unit.opcode tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.control_unit.instr tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu.instr_i tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu.instr_r tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu.instr_s tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu.instr_sb tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu.instr_u tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu.instr_uj tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.fetch_stage_i.pc tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.fetch_stage_i.npc tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.load_type tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.alu_a_sel tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.alu_b_sel tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.alu_op tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.branch tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.branch_type tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.breakpoint tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.csr_addr tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.csr_clr tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.csr_imm tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.csr_rw_valid tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.csr_set tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.csr_swap tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.dren tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.dwen tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.ecall_insn tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.ex_pc_sel tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.fault_insn tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.halt tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.ifence tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.illegal_insn tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.imm_I tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.imm_S tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.imm_SB tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.imm_U tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.imm_UJ tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.imm_shamt_sel tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.instr tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.j_sel tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.jump tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.opcode tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.ret_insn tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.shamt tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.w_sel tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.wen tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.cu_if.zimm
probe -create -database waves tb_RISCVBusiness_self_test.DUT.pipeline.tspp_pipeline.execute_stage_i.rf.registers

simvision -input priv.tcl.svcf
