name: Test
on:
  push:
  pull_request: 
    branches: [63-fix-cicd]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # required
      - name: Run Regression Tests
        uses: Purdue-SoCET/SoCET-CI@63-fix-cicd # core usage
        with:
          targets: | # List all FuseSoC Test Targets
            make config
            make verilate

            fusesoc --cores-root . run --target sim_tlb_directmapped socet:riscv:tb_supervisor:0.1.0 --make_options='-j'
            fusesoc --cores-root . run --target sim_tlb_associative socet:riscv:tb_supervisor:0.1.0 --make_options='-j'
            fusesoc --cores-root . run --target sim_page_walker socet:riscv:tb_supervisor:0.1.0 --make_options='-j'
            fusesoc --cores-root . run --target sim_supervisor_cache socet:riscv:tb_supervisor:0.1.0 --make_options='-j'